#!/usr/bin/env python3
"""Build the DevTool's profile-key reference from the Lost Cities jar.

    python mod/tools/extract-profile-keys.py

Writes `mod/src/main/resources/data/lostcitiesdevtool/profile_keys.json`, which the
mod loads to put a key's own description behind a hover in chat. A person reading a
report should not have to leave the game to find out what `ruinChance` means.

Two sources, merged:

  the jar          Every `Configuration.get*` call in `LostCityProfile` carries the
                   key, its section, and the **comment the mod itself writes into
                   the config file**. The comment is the last string pushed before
                   the call, which the wiki's own extractor reads and discards.

  mod-keys.json    Type, minimum, maximum and default, already extracted and already
                   checked against the published tables.

Nothing here is authored. If the two disagree about a key existing, that is a bug in
one of the extractors and this script says so rather than picking a winner.
"""
import io
import json
import os
import re
import subprocess
import sys
import tempfile
import zipfile

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(HERE)
REPO = os.path.dirname(MOD)

JAR = os.path.join(MOD, "libs", "lostcities-1.20-7.4.12.jar")
KEYS = os.path.join(REPO, "docs", "examples", "mod-keys.json")
OUT = os.path.join(MOD, "src", "main", "resources", "data", "lostcitiesdevtool",
                   "profile_keys.json")
VERSION = "7.4.12"

PROFILE_CLASS = "mcjty/lostcities/config/LostCityProfile.class"
IDENT = re.compile(r"^[A-Za-z_][A-Za-z_0-9]*$")
GETTER = re.compile(r"Configuration\.get(Boolean|Int|Float|Double|String|StringList)")


def javap():
    for cand in (os.environ.get("LCRIG_JAVAP"), "javap",
                 r"C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/javap.exe"):
        if not cand:
            continue
        try:
            subprocess.run([cand, "-version"], capture_output=True, timeout=20)
            return cand
        except Exception:
            continue
    raise SystemExit("no javap found. Set LCRIG_JAVAP or put a JDK on PATH.")


def comments():
    """{key: the comment the mod writes above it in the config file}."""
    with zipfile.ZipFile(JAR) as z:
        blob = z.read(PROFILE_CLASS)
    with tempfile.TemporaryDirectory() as d:
        p = os.path.join(d, "X.class")
        io.open(p, "wb").write(blob)
        text = subprocess.run([javap(), "-p", "-c", "-constants", p],
                              capture_output=True, text=True).stdout

    out, strings = {}, []
    for line in text.splitlines():
        m = re.search(r"//\s+String\s+(.*?)\s*$", line)
        if m:
            strings.append(m.group(1))
            continue
        g = GETTER.search(line)
        if g:
            # Count from the END. Each getter takes its key, its section and its
            # comment, and getString takes a default between them. Reading forwards
            # picks up whatever the previous statement left behind.
            want = 4 if g.group(1) == "String" else 3
            window = strings[-want:] if len(strings) >= want else strings
            if len(window) >= 2 and IDENT.match(window[0]) and IDENT.match(window[1]):
                out[window[0]] = window[-1].replace("\\'", "'")
            strings = []
        elif len(strings) > 12:
            strings = strings[-12:]
    return out


def main():
    if not os.path.isfile(JAR):
        raise SystemExit("no %s. The jar is compile-only and gitignored." % JAR)

    said = comments()
    meta = json.load(io.open(KEYS, encoding="utf-8"))["versions"][VERSION]["profile"]

    only_jar = sorted(set(said) - set(meta))
    only_meta = sorted(set(meta) - set(said))
    if only_jar or only_meta:
        print("the two extractors disagree, which is a bug in one of them:")
        for k in only_jar:
            print("  comment but no metadata:", k)
        for k in only_meta:
            print("  metadata but no comment:", k)

    doc = {"_about": "Generated by mod/tools/extract-profile-keys.py. Do not edit.",
           "version": VERSION, "keys": {}}
    for key in sorted(set(said) & set(meta)):
        entry = {"section": meta[key].get("section"),
                 "type": meta[key].get("type"),
                 "comment": said[key]}
        for extra in ("min", "max", "default"):
            if extra in meta[key]:
                entry[extra] = meta[key][extra]
        doc["keys"][key] = entry

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(
        json.dumps(doc, indent=1, ensure_ascii=False) + "\n")
    print("%d keys written to %s" % (len(doc["keys"]),
                                     os.path.relpath(OUT, REPO)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
