package com.rinkynooble.lostcitiesdevtool.workshop;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nullable;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Which rows of plots the workshop needs, for the version being targeted.
 *
 * <p>Generated by {@code mod/tools/extract-catalogue.py} from the same key export
 * the wiki's reference tables are checked against, so the catalogue cannot offer a
 * shape the mod does not declare. What the script adds by hand is the
 * classification, because that is knowledge rather than data.
 */
public final class Catalogue {

    /**
     * How a row's variations behave, which is the whole reason the settings differ
     * between rows.
     */
    public enum Kind {
        /**
         * Streets, highways, railways. {@code Tools.listOrStringList}, so a bare
         * string or an unbounded list, picked uniform random. No weight anywhere.
         */
        PART_LIST,
        /**
         * Monorails. Plain {@code Codec.STRING}: a list is a load error, so the row
         * holds exactly one plot and can never hold two.
         */
        SINGLE,
        /**
         * Buildings, parks, fountains and the rest. {@code ObjectSelector}, so every
         * entry carries a required {@code factor} and optional distance gating.
         */
        SELECTOR;

        static Kind of(String s) {
            return switch (s) {
                case "single" -> SINGLE;
                case "selector" -> SELECTOR;
                default -> PART_LIST;
            };
        }
    }

    /** East of the origin, or west of it. Rows grow away from the origin either way. */
    public enum Area { EAST, WEST }

    /**
     * One row.
     *
     * @param owner the asset the names end up in. A row owned by the city style has
     *              to say which city style, because a pack may have several; a row
     *              owned by the world style has exactly one place to go.
     * @param dead  set when the shape parses and never generates. Kept in the
     *              catalogue rather than hidden, and flagged.
     */
    public record Row(String id, String family, String key, Area area, Kind kind,
                      String owner, int plots, int width, int height,
                      @Nullable String dead) {

        public boolean cityStyleScoped() {
            return "citystyle".equals(owner);
        }
    }

    private static final String PATH = "/data/lostcitiesdevtool/catalogue.json";

    /**
     * Volatile because these are published from one thread and read from others.
     *
     * <p>Every caller is on the server thread today, and that is an invariant nothing
     * enforces. Without volatile the failure mode is unsafe publication: a reader sees
     * the reference before the object it points at is fully built. That appears once,
     * on somebody else's machine, and never reproduces. `Json5Overrides` in this same
     * codebase already does it this way.
     */
    private static volatile List<Row> rows;
    private static volatile String version = "unknown";

    /**
     * Its own logger rather than the mod entry point's.
     *
     * <p>The catalogue is data loading and nothing else. Reaching through
     * {@code LostCitiesDevTool} for a logger dragged Forge onto the classpath of a
     * class that needs Gson, which put the layout out of reach of a plain JVM test.
     */
    private static final Logger LOGGER = LoggerFactory.getLogger("lostcitiesdevtool");

    private Catalogue() {
    }

    public static List<Row> rows() {
        if (rows == null) {
            rows = load();
        }
        return rows;
    }

    public static String version() {
        rows();
        return version;
    }

    @Nullable
    public static Row row(String id) {
        for (Row r : rows()) {
            if (r.id().equals(id)) {
                return r;
            }
        }
        return null;
    }

    private static List<Row> load() {
        try (InputStream in = Catalogue.class.getResourceAsStream(PATH)) {
            if (in == null) {
                LOGGER.error("no {} on the classpath", PATH);
                return Collections.emptyList();
            }
            JsonObject root = JsonParser.parseReader(
                    new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
            if (root.has("version")) {
                version = root.get("version").getAsString();
            }
            List<Row> out = new ArrayList<>();
            for (JsonElement e : root.getAsJsonArray("rows")) {
                JsonObject o = e.getAsJsonObject();
                int w = o.getAsJsonArray("size").get(0).getAsInt();
                int h = o.getAsJsonArray("size").get(1).getAsInt();
                out.add(new Row(o.get("id").getAsString(),
                        o.get("family").getAsString(),
                        o.get("key").getAsString(),
                        "east".equals(o.get("area").getAsString())
                                ? Area.EAST : Area.WEST,
                        Kind.of(o.get("class").getAsString()),
                        o.get("owner").getAsString(),
                        o.get("plots").getAsInt(), w, h,
                        o.has("dead") ? o.get("dead").getAsString() : null));
            }
            return Collections.unmodifiableList(out);
        } catch (Exception e) {
            LOGGER.error("could not read {}: {}", PATH, e.toString());
            return Collections.emptyList();
        }
    }
}
